### ISSUE TITLE
Technical seems a little unfocused

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#10]
[https://github.com/IDPros/bok/blob/bok-edit/IAM%20Architecture/Technical/Technical.md](url)

This article contains many assertions don't seem a propos. For example:

> Most organizations that maintain an enterprise architecture start with the Technical Architecture (TA). It's the component that delivers the greatest return on investment.
>The sooner an organization can limit the number of supported patterns, the greater the savings on the IT budget.

It seems like there are some good points here, but perhaps a more methodical development with an example or two would be good.

**Comment by GrahamWilliamson** [comment]
OK - I'll re-write.

**Comment by GrahamWilliamson** [comment]
The Technical Architecture section has been re-written to address these issues
