### ISSUE TITLE
IAM Project Management Article Review

### ISSUE THREAD

**Issue by vsnt** [IDPros/bok#105]
Feedback for article, [Introduction to Project Management for IAM Projects (v2)](https://bok.idpro.org/article/id/25/)

1. It might be useful to include some examples of typical IAM projects (public sector, private sector, workforce, customer security upgrade, MFA, implementing new IAM tech) and what might be included in the scope. 
2. If possible, identify & share which and what kinds of variables that could influence project scope.
3. It may be useful to identity cross-organizational roles that support the success of a project: one of the lesson's from Ian's Identiverse presentation, was to hire a writer early on, and ensure they understood the changes, and then the writer could not only clearly write about the tech for end customers but could also work with marketing and other parts of the organization.. 
4. It could be useful to include guidance on interacting with executive management, end customers and other roles in a company, or roles you may work with in an external vendor & best practices to leverage the talents of those roles. 
5. In the control section, please expand the examples of these. The second one could use better explanation - maybe a table - and include pros/cons or reasons when one may be more appropriate than another. At least add headers for each of the examples mentioned.

**Comment by hlflanagan** [comment]
Article has been updated (from changelog: "Substantive revisions to Planning Stage, Agile; new section on Organizational Variances"). See https://bok.idpro.org/article/id/25/
