### ISSUE TITLE
use of "delegation" in Cloud Service Authenticates Via Delegation - SAML

### ISSUE THREAD

**Issue by hlflanagan** [IDPros/bok#107]
(From Vittorio Bertocci on the IDPro Slack)
I was curious sbout the use of "delegation" in the context of SAML, so I opened the article... the word occurs only 3 times, and all those are in titles rather than in the body/discussion. Wondering whether that means it might be misleading and/or could be cut?

**Comment by cronical** [comment]
PR 114
