### ISSUE TITLE
Introduction to Privacy and Compliance for Consumers (v2) Article Review

### ISSUE THREAD

**Issue by vsnt** [IDPros/bok#108]
Introduction to Privacy and Compliance for Consumers (v2)
https://bok.idpro.org/article/id/44/

Is the topic still relevant? Yes, absolutely, and more than ever.
Is the information still accurate? Yes, but this is an ever growing/evolving topic.
Is the information complete? It's good, and things have changed since the last publish.

General comments
This topic can expand to be as long as we wish to write. That said, upon reading here are a few comments:

- Could be useful to review new privacy concerns, especially around: OSINT, politicization & weaponization of data, also around swatting, online bullying, revenge porn. These can be worse case scenarios, especially when the individuals are political targets. 
Privacy as a competitive advantage - I think we will start seeing this tick up, but still not at the tipping point. Still, part of this problem is that consumers do not really have a choice with many of today's offerings.
- Status of regulation, GDPR and other regulations
- Innovation to address GDPR - EU innovation with Decentralized Identity
- How much is too much privacy. Hiding behind anonymous, the importance of identifying bots, and mis/disinformation
- Any additional insightful expert perspectives - rebutting the need for "real names." Seems like newbies to the identity space first think the easy solution is to require real names - what about proactively refuting this concept as unuseful.
- Might want to include Schneier's click here to kill everyone. Not required.
- New perspective: consumer privacy in the context of government interaction: voting, city government, benefits. How can you ensure privacy when governments must provide services to all members of society, not just a private sector target market.
- Technologies that promise identity: Decentralized identity (DIDs and VCs) promise sharing with security and privacy. DI has matured (especially in Europe) the past couple years. 
- Most importantly, organizations need to ask of the data they collect, "How can this data be weaponized against a consumer?"

**Comment by hlflanagan** [comment]
Thank you for the review! We've updated the article where we could, recognizing that it would benefit from a subject-matter expert to come in and give a thorough update and expansion. The revised article was published 15 December 2022.
