### ISSUE TITLE
repositories

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#11]
[https://github.com/IDPros/bok/blob/bok-edit/IAM%20Architecture/Technical/Repositories/Repositories.md](url)

As an introduction to the universe of repositories this is generally good.  However, I think it will be very hard to consume... maybe it's covering too much for one article.

I think there is an error on the LDAP access control point 
>  Anyone with an LDAP filter, with knowledge of the directory, can do a bind to the directory and retrieve data from it. 

That can be fixed with proper access control internal to the directory.  

Each one of the headings in this should probably be detailed in a lower level document.

Missing is the heading for Virtual Directory

**Comment by GrahamWilliamson** [comment]
OK - I'll re-write.

**Comment by GrahamWilliamson** [comment]
Done - awaiting update to master
