### ISSUE TITLE
Best title for Cloud Services Authentication via delegation - SAML

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#113]
Great comments @msfthiker on issue 110. I'm struggling a bit with what a better title would be. I can see that Cloud Services could be a misleading title.

What do you think of

Browser uses web-based application which delegates authentication

?

**Comment by msfthiker** [comment]
Delegated authentication using SAML web browser SSO profile?

SAML - Web browser SSO profile (basically lifting the profile name from the spec)?

**Comment by cronical** [comment]
Great suggestionsl.  I prefer the first. @hlflanagan can you make the change to the title?

**Comment by hlflanagan** [comment]
Done. This will be reflected in the new release on 15 December.
