### ISSUE TITLE
Introduction to Identity - Part 1: Admin-time

### ISSUE THREAD

**Issue by CipherQueen** [IDPros/bok#17]
Fantastic! Some comments.

For the abstract, please include "run-time," not just "admin-time." Unless a person attended the Identiverse 2019 talk that introduced these terms, they are foreign.

The section on "Privileged Account Management" could include a wider scope, especially if it was called "Privileged Access Management." Is this by design? For IDPro BoK Section 3.2.3 the heading is "Privileged Access Management." There are many terms in this space, including PIM. Just curious how we have defined them.

**Comment by hlflanagan** [comment]
It's taken a while, but we're now at the point of refreshing the article. I've proposed an update to the abstract to include "IAM technologies and use cases that focus on active, live interactions, or run-time, are mentioned for comparison."

For Privileged Account Management, the BoK needs an article (or even an entire set of articles) just on that topic. It is only introduced here to make sure people are aware of the term.

**Comment by hlflanagan** [comment]
A refreshed version is now available. Thank you for the feedback!
