### ISSUE TITLE
Proposed enhancement for Intro to Project Management

### ISSUE THREAD

**Issue by hlflanagan** [IDPros/bok#25]
Would be nice to have some contextualization for organizations of different sizes or types (e.g. nonprofits, etc.) but agree that it works as an intro.

**Comment by GrahamWilliamson** [comment]
While all sizes and types of organisations need to adopt project management it would be worthwhile discussing this topic in the PMO section.

**Comment by hlflanagan** [comment]
Many thanks to Graham for updating the article! A refreshed version is in this repository now and will be published on the IDPro website tomorrow.
