### ISSUE TITLE
Consider adding more information for the IAM practitioner working with a PMO

### ISSUE THREAD

**Issue by hlflanagan** [IDPros/bok#26]
Consider adding more guidance on how an IAM practitioner can navigate the PMO and other organizational entities successfully. A “how to partner with your project manager” would be a great follow-up.

**Comment by GrahamWilliamson** [comment]
Agree - the PMO section should be expanded to provide guidance to IAM professionals.

**Comment by coremania** [comment]
Hmm, maybe more use-cases would help here, with an eye to specific experiences that the authors could relate...

**Comment by GrahamWilliamson** [comment]
It depends on how detailed we want to get. The PMO should be very useful to a IAM practitioner - i.e. he/she can hand over the administration of the project to a PMO resource that will push the project through the gates. The biggest benefit is the visibility to the organization's development program. THe PMO schedule should show what apps are bing updated and could potentially adopt better IAM processes. My experience is the many projects don;t address IAM issues in the planning stage and when the IM team approacehes them during developmet they're told it's too late.
My own experience with PMOs has not been good - if they are bureaucratic bodies that are only intereted in getting projects through the 'process' they can be difficult to work with.
Do we need to add more detail?
Thx. Graaham

**Comment by cronical** [comment]
I’m not sure how to fit this in, but I am seeing companies moving away from PMO (possibly due to the performance level implied by Graham’s observation) in favor of persistent cross functional teams under heading of “agile”.  You could say this involve project management by another name. But it also changes the approach to attach identity concerns to their product.

**Comment by hlflanagan** [comment]
Many thanks to Graham for updating the article! A refreshed version is in this repository now and will be published on the IDPro website tomorrow.
