### ISSUE TITLE
Knowledge sharing links

### ISSUE THREAD

**Issue by gbd-idpro** [IDPros/bok#30]
Wid and kantara links are left over from internal corporate redirects.  Example

https://urldefense.proofpoint.com/v2/url?u=http-3A__www.womeninidentity-2Corg&d=DwMFaQ&c=w_KKIrnflabZu7RVO9QOig&r=sUURud0DEGZlrJY1d720YbU5NxCCGtBCPJEmfgWd8PM&m=pkK4m6dkmKfHBhhBc79iGn6bxFoyQ5QKTJ1wodnmpEk&s=kTxMCZW2kXuc4ABocN2hmNZKgOuvceILgjrb0R0oWhg&e=

This one actually failed for me.

**Comment by mark-drummond** [comment]
That would be a copy-paste from my work email. I'll see what I need to do to get it fixed.

**Comment by dmark** [comment]
I have updated the links the source doc for WomenInID, and I am checking the others. (@mark-drummond is Work Me).

**Comment by dmark** [comment]
I have reviewed the other source docs and updated the links. I'll get these into the queue for the next release.

**Comment by hlflanagan** [comment]
Fixed
