### ISSUE TITLE
BoK Annual review - Introduction to Project Management for IAM Projects

### ISSUE THREAD

**Issue by meneer** [IDPros/bok#33]
In my opinion the article should be updated and expanded.
A few issues with this document:
- it looks like the authors picked some theoretical models, but why these for IAM?
- nothing specific about project management for IAM
- the IAM specific parts are the activities for a business consultant, part of a project, but it can be so much more.

My suggestion is to skip the regular PM theory and focus solely on what makes an IAM project complex:

- Business domain (Access Control and Governance)
- IT domain (technology, just like a normal IT project)
- Waterfall-like for regular 1st phase IGA and Agile for extending the scope or for B2B/B2C/IoT projects

Especially Business focus: IAM is Organizational Change, not just IT ops.

**Comment by GrahamWilliamson** [comment]
The document's been updated to more clearly reflect IAM project management issues.
The model used is not theoretical it's standard PMI framework.
We should not skip the PM theory - that's the whole problem - too many IAM project do.

**Comment by hlflanagan** [comment]
Many thanks to Graham for updating the article! A refreshed version is in this repository now and will be published on the IDPro website tomorrow.
