### ISSUE TITLE
IAM Solution Architecture

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#4]
[https://github.com/IDPros/bok/blob/bok-edit/IAM%20Architecture/Introduction.md](url)

This section is focused on the Enterprise view.  That would be OK if it's listed as such.

**Comment by GrahamWilliamson** [comment]
No it's not OK - we need tofocus on Solution Archtiecture.
Maybe we need to address this at Enterprise and SMB levels?

**Comment by cronical** [comment]
I think Enterprise and SMB are distinguished by scale but are the same basic problem.  The one I was thinking about is the customer/citizen side. 

Maybe best at the top level of architecture to handle both.  Then if need be distinguish further down.?
