### ISSUE TITLE
Cormack: An Introduction to the GDPR: Necessary for the Performance of a Contract

### ISSUE THREAD

**Issue by ancormack** [IDPros/bok#41]
Please add to second paragraph.
After current "... The latter should use the basis of “consent” described below. The European Data Protection Board’s Guidelines [https://edpb.europa.eu/sites/default/files/files/file1/edpb_guidelines-art_6-1-b-adopted_after_public_consultation_en.pdf] clarify that ancillary functions including service improvement, fraud prevention and online behavioural advertising are likely to need a different legal basis."

**Comment by hlflanagan** [comment]
Article has been updated. Thank you!
