### ISSUE TITLE
Cormack: An Introduction to the GDPR: International Transfers

### ISSUE THREAD

**Issue by ancormack** [IDPros/bok#42]
Replace "Arrangements for international transfers" to "aware of developments" with a new paragraph:

Arrangements for international transfers are subject to change: for example both the original US Safe Harbor scheme and the Privacy Shield that replaced it have been declared invalid by the European Court of Justice; the latter case (“Schrems II”) also added new obligations for exporting organisations using the Standard Contract Clauses, with new versions of the Clauses currently being proposed by the European Commission. Organisations operating international IAM systems should be aware of developments.

**Comment by hlflanagan** [comment]
Article has been updated. Thank you!
