### ISSUE TITLE
BSA - project mangement

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#5]
[https://github.com/IDPros/bok/blob/bok-edit/IAM%20Architecture/Business%20System%20Architecture/Business%20System%20Architecture.md](url)

Project management concerns mixed in with BSA: 

> It is important for the identity management professional to select the level of detail required in understanding these systems. In any one IAM project only a subset of systems will be included; to try and include them all will result in "boil the ocean" syndrome which will severely reduce the likelihood of project success.

**Comment by GrahamWilliamson** [comment]
More information please - can't see where the PM concerns are mentioned?

**Comment by cronical** [comment]
"It is important for the identity management professional to select the level of detail required in understanding these systems. In any one IAM project only a subset of systems will be included; to try and include them all will result in "boil the ocean" syndrome which will severely reduce the likelihood of project success.

It's good advice.  Just seems out of place here.

**Comment by GrahamWilliamson** [comment]
This section has been updated.
