### ISSUE TITLE
BSA - subsection(s)?

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#6]
[https://github.com/IDPros/bok/blob/bok-edit/IAM%20Architecture/Business%20System%20Architecture/Business%20System%20Architecture.md](url)

The recertifications section seems like  it needs its own section along with the other 3 items listed under the process maps.

**Comment by GrahamWilliamson** [comment]
The Recertification of accounts is it's own section - should it be raised to a higher level?
Re: Joiners, Movers & Leavers - I can write a separate section on each - but it might make the document too bloated. I would vote - leave them together in a "provisioning " section.

**Comment by cronical** [comment]
I think we might need a professional editor.  Assigning to HLF
