### ISSUE TITLE
AuthN definition improvement

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#63]
in article 42, there are 2 definitions of AuthN.  The one that made it to the terminology session combines other concepts, notably trustworthiness and authorization.  The cleaner version is in the text as follows and should be used in the terminology section after extension.

"Authentication is the process of proving that the user with a digital identity who is requesting access is the rightful owner of that identity."

The extension needed is in the current definition - which includes users and applications as principals.  

Current: "Authentication – The ability to prove that a user or application is trustworthy and has the authority to access a protected resource by validating credentials of an access requester (a user, a process, a system, or a thing)."

**Comment by meneer** [comment]
Agreed

In termnology change to: 
Authentication is the process of proving that the user with a digital identity who is requesting access is the rightful owner of that identity.

**Comment by hlflanagan** [comment]
Revised article published
