### ISSUE TITLE
Refresh of Introduction to Identity - Part 2

### ISSUE THREAD

**Issue by hlflanagan** [IDPros/bok#64]
See https://bok.idpro.org/site/article-refresh-process/

https://bok.idpro.org/article/id/45/

**Comment by hlflanagan** [comment]
From Mark Cox: The article is still accurate, relevant, and complete. No change required.

**Comment by GrahamWilliamson** [comment]
A good and relevant article. No change required.

**Comment by deano5111** [comment]
Excellent read. The article is still accurate, relevant, and complete. No change required.

**Comment by hlflanagan** [comment]
Thank you all for your reviews!
