### ISSUE TITLE
Refresh of Introduction to Access Control

### ISSUE THREAD

**Issue by hlflanagan** [IDPros/bok#65]
See https://bok.idpro.org/site/article-refresh-process/

https://bok.idpro.org/article/id/42/

**Comment by hlflanagan** [comment]
From Mark Cox: The article is still accurate, relevant, and complete. No change required.

**Comment by deano5111** [comment]
In my opinion: The article is still accurate, relevant, and complete. No change required.

**Comment by hlflanagan** [comment]
Thank you for your reviews!
