### ISSUE TITLE
Federation in the Enterprise - IdP and SP Support Limitations

### ISSUE THREAD

**Issue by lukealton** [IDPros/bok#70]
In the "Federation in the Enterprise" article there is a statement that "Some applications only support IdP-initiated login requests.". While that is certainly true I also frequently encounter service providers who only support SP-initiated login requests.

Suggested updated language:

"Some applications only support login requests initiated from either the IdP or the SP, and not both scenarios."

**Comment by hlflanagan** [comment]
Wow I'm really late on closing this one. This issue was addressed in v2 of the doc.
