### ISSUE TITLE
Technical & Grammatical error in published article

### ISSUE THREAD

**Issue by Credentive-Sec** [IDPros/bok#73]
https://github.com/IDPros/bok/blob/edf8cd8466d05c81946059adfa5bc5832c86794b/Digital%20Identity/practical-implications-PKI.md#L528

In the section on "Factors and Problems Limiting PKI Adoption," there is a discussion of Enterprise Key Management Challenges. It reads in part: "Vendors, meanwhile, have implemented sophisticated, proprietary solutions for the automation of key management. Microsoft Active Directory Certificate Services can provide key management and certificate services for machines and human users in an Active Directory environment. The Entrust Certificate Authority provides a client-side tool that will manage key and certificate lifecycle for the clients with the tool installed. _**OpenSSL offers a free, open-source solution for**_ These tools are designed to support a closed system."

I made a mistake here. There are two issues - an embedded sentence fragment, and more importantly, the OpenSSL reference in this paragraph is not correct because OpenSSL does not bundle any tools for automation of key lifecycle management."

**Comment by hlflanagan** [comment]
How did I miss this??? This has been fixed.
