### ISSUE TITLE
Revision of An Overview of the Digital Identity Lifecycle - cycle

### ISSUE THREAD

**Issue by meneer** [IDPros/bok#74]
An Overview of the Digital Identity Lifecycle by Authors: Andrew Cameron (GM) , O. Grewe (IDPro) 

The life cycle images show circular tracks, whereas the track will probably not be circular. Example:
Figure 1: there is an arrow pointing from De-provision Access to Create Identity.
It's not clear what this means. If de-provision access means delete identity, or archive identity, that an arrow can exist only if create idenitty reactivates the deactivated identity. It should never just create a new identity. 

This is also true for the other images.
In figure 3 De-Provision Access would better be called Decommission identity / device, whatever and no arrow pointing to create again.

**Comment by hlflanagan** [comment]
Figures have been updated. See https://github.com/IDPros/bok/blob/master/Digital%20Identity/digital-identity-lifecycle-final.md
