### ISSUE TITLE
Revision of An Overview of the Digital Identity Lifecycle - authenticate

### ISSUE THREAD

**Issue by meneer** [IDPros/bok#75]
The authenticate part is not (always) part of the lifecycle.
In figure 1, instead of authenticate, perhaps Identity Proofing can be used, but that should be done at the start of the process.
In figure 2, authentication in an IDaaS environment is done before accessing services using the account, but at identity lever, but at account level. Once an identity and an account is creates, the account will be reused, after authenticating the rightful ownership of the account.
In figure 3, authentication will occur after every commission or change of a compent. But then the session can stay on for ever, until decomisioning 

Authenticate in all figures is about authentication of account usage, not of identity, prior to access, perhaps as part of access control.

**Comment by hlflanagan** [comment]
Figures have been updated. See https://github.com/IDPros/bok/blob/master/Digital%20Identity/digital-identity-lifecycle-final.md
