### ISSUE TITLE
Use of Contoso/Fabrikam in Decentralized Identity article

### ISSUE THREAD

**Issue by deansaxe** [IDPros/bok#79]
Contoso and Fabrikam are used in Microsoft-specific documentation and should be removed from IDPro BoK articles to reinforce the idea of a vendor-neutral set of articles.

https://bok.idpro.org/article/id/51/

**Comment by hlflanagan** [comment]
Article has been updated with new example names. See https://github.com/IDPros/bok/blob/master/Digital%20Identity/a-peek-into-the-future-of-decentralized-identity-final.md
