### ISSUE TITLE
App Portfolio

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#8]
[https://github.com/IDPros/bok/blob/bok-edit/IAM%20Architecture/Application%20Portfolio/Application%20Portfolio.md](url)

The 1st sentence of the 2nd paragraph should come 1st.  It establishes the purpose.

> Critical to the IAM environment is the ability to support a wide variety of applications from legacy client-server apps to cloud-based containerized apps. 

The logic of APIs needs to be developed more fully.  Due to legacy constraints it is not always possible to use APIs so this needs to be a bit more nuanced.

The sentence

> It is important that the identity management professional ensures the development of the IAM environment is aligned with the deployment of new applications and development of legacy applications

should lead the 1st paragraph.  The App Portfolio is probably too prescriptive to be general.  Certainly a good idea but perhaps it could be generalized and let the detailed list of attributes fall more in the "how to" category.

**Comment by GrahamWilliamson** [comment]
Yup - rearrange the sentences.
Not sure what is meant be the AP is too prescriptive to be general - does it need detail removed, or should the diagram be removed?

**Comment by cronical** [comment]
I didn't realize there was a diagram.  This may have gotten lost somewhere.  Will open a separate issue for that.  

When I read the text, I felt the list of attributes for the application portfolio was prescriptive, not illustrative.   I bet the diagram helped.  Just thinking that all those attributes won't apply in all environments.

**Comment by GrahamWilliamson** [comment]
The Application Portfolio section has been updated
The diagram is the example showing an extract from the AP document.
