### ISSUE TITLE
diagram not rendering in web view - Introduction to IAM Architecture (v2)

### ISSUE THREAD

**Issue by coremania** [IDPros/bok#81]
Hi there, I see that Figure 7 in the web view of this document (https://bok.idpro.org/article/id/38/) renders like this on the page; 

img src="image7.png" style="width:3.38333in;height:1.54167in" alt="Hybrid Cloud diagram" />
Figure 7: Hybrid Cloud Identity Architecture model

**Comment by coremania** [comment]
I also notice that Graham's picture is not rendering in the bio section at the bottom of the document.

**Comment by hlflanagan** [comment]
Fixed. Thanks!
