### ISSUE TITLE
author finds own typo in Volume 1, Issue 1 article "Review - ISO/IEC 24760-1:2019"

### ISSUE THREAD

**Issue by coremania** [IDPros/bok#83]
Link to article: https://bok.idpro.org/article/id/18/

The sentence below should read "probably use this one", so please remove the extra "to".

This document intends to provide authoritative definitions of terms and concepts, so other documents **probably use to this one** as a reference document.

**Comment by hlflanagan** [comment]
Fixed. Thanks!
