### ISSUE TITLE
Federation in the Enterprise - title or content change suggestion

### ISSUE THREAD

**Issue by meneer** [IDPros/bok#88]
It's a good article, but title and content don't match. There is no content that lifts the federation content to enterprise level, it's a good federation explanation. But it covers generic OIDC/SAML.

Either drop the 'in the enterprise' part in the title, or add enterprise relevant content to the article

Additional enterprise level content could be architectural insights and design concepts around internal versus externel use of OIDC/SAML, internal versus external IdP's and SP's, explaining the federation contract concept and adding some content about the use of federation as a requirement for Zero Trust and PBAC.

https://github.com/IDPros/bok/blob/a8e1b81f9a86457dc5d7090b23e60adb04962d73/Architecture/Enterprise-Identity-Federation-final.md

**Comment by hlflanagan** [comment]
Addressed in #101
