### ISSUE TITLE
Info Arch.

### ISSUE THREAD

**Issue by cronical** [IDPros/bok#9]
[https://github.com/IDPros/bok/blob/bok-edit/IAM%20Architecture/Information%20Architecture/Information%20Architecture.md](url)

> In many cases the IAM system will maintain its own data repository of identity data i.e. maintain an interface to the HR system and to relying applications via connectors that update the IAM system.

Its too specific to call out the HR system as the only book of record.  In fact, in many environments there are multiple BORs. (e.g. contractors, business partners, subsidiary's HR systems....).  Maybe just say "e.g. in a simple case HR often selected as the source of employee records".

The section

> Increasingly organizations are seeking to maintain a directory that is the "source of truth" for identity information within the organization and each application maintains a connector to this repository which is typically an electronic directory. In some cases this is an LDAP directory, in Microsoft environments it is increasingly Active Directory (AD) or Azure AD. A central repository simplifies the IAM task but in many cases applications are not designed to use an external directory, they maintain their own internal databases of identity and account permission information.

talks about the instantiation of the data elements.  This approaches then crosses the border into technical architecture (IMO).  Likewise the note about technical and political issues feels out of place in an the IA discussion.

**Comment by GrahamWilliamson** [comment]
Yup - I'll change to widen the reference to other sources of identity data.
I don't like BoR - I prefer "Authoritative source" as the "master" for identity attributes
The identity provider service i.e. directory is the "source of truth" - OK?

**Comment by cronical** [comment]
I agree - Authoritative Source is better than Book of record.
