### ISSUE TITLE
Article Update Required - Introduction to Identity - Part 1: Admin-time (v2)

### ISSUE THREAD

**Issue by kzaky** [IDPros/bok#96]
I was recently reviewing this [article](https://bok.idpro.org/article/id/27/) in the BoK and it seems like the [linked PDF](https://bok.idpro.org/article/27/galley/94/view/) is missing some of the items in the terminology section on the [page](https://bok.idpro.org/article/id/27/).

**Comment by hlflanagan** [comment]
Not sure how that happened! I think it's all been updated, though, with the v2 release of the article.

**Comment by kzaky** [comment]
No worries! Thank you @hlflanagan for looking into this 🙌🏽
