### ISSUE TITLE
AuthN/AuthZ article feedback

### ISSUE THREAD

**Issue by kzaky** [IDPros/bok#97]
In the AuthN/AuthZ article it references that "Authentication is the process of proving that the user with a digital identity who is requesting access is the rightful owner of that identity." is that true or should be reworded that the user with the digital identity has the right credentials. I think ownership is separate from authentication. Having the keys to the house doesn't mean I own the house. We can argue that malicious actors doing credential stuffing attacks are authenticated but not rightful owners of the identity but rather have the right credentials.

**Comment by cronical** [comment]
This is a fair point.  Welcome to the ongoing search for the perfect definition of AuthN.

**Comment by hlflanagan** [comment]
Thank you for the feedback! The article has been updated and v2 released as of 16 December 2022.
